// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using KTC_Scraper.Interfaces;
using KTC_Scraper.Models;
using Microsoft.EntityFrameworkCore;

namespace KTC_Scraper.Contexts
{
    public partial class KtcContext : DbContext, IKtcContext
    {
        private readonly IConnectionString _connection;
        public KtcContext(ConnectionString connection)
        {
            _connection = connection;
        }

        public KtcContext(DbContextOptions<KtcContext> options)
            : base(options)
        {
        }

        public virtual DbSet<NflSchedule> NflSchedules { get; set; }
        public virtual DbSet<OneQbValue> OneQbValues { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<SuperflexValue> SuperflexValues { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                string connection = _connection.ConnectionStringVal("ktcContext");
                optionsBuilder.UseSqlServer(connection);
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            OnModelCreatingPartial(modelBuilder);
            modelBuilder.Entity<Player>().Property(et => et.playerID).ValueGeneratedNever();
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}