CREATE TABLE [dbo].[Value]
(
	[ValueId]				INT				NOT NULL PRIMARY KEY,
	[ScoringTypeId]			INT				NOT NULL,
	[Value]					INT				NULL,
	[StartSitValue]			INT				NULL,
	[Rank]					INT				NULL,
	[OverallTrend]			INT				NULL,
	[PositionalTrend]		INT				NULL,
	[RookieTrend]			INT				NULL,
	[RookiePositionalTrend]	INT				NULL,
	[History]				VARCHAR(128)	NULL,
	[Kept]					INT				NULL,
	[Traded]				INT				NULL,
	[Cut]					INT				NULL,
	[Diff]					INT				NULL,
	[OverallTier]			INT				NULL,
	[PositionalTier]		INT				NULL,
	[RookieTier]			INT				NULL,
	[RookiePositionalTier]	INT				NULL,
	[Overall7DayTrend]		INT				NULL,
	[Positional7DayTrend]	INT				NULL,
	[StartSitOverallRank]	INT				NULL,
	[StartSitPositionalRank]INT				NULL,
	[StartSitOverallTier]	INT				NULL,
	[StartSitPositionalTier]INT				NULL,
	[StartSitOneQBFlexTier]	INT				NULL,
	[StartSitSuperFlexTier]	INT				NULL,
	[IsOutThisWeek]			BIT				NULL,
	FOREIGN KEY (ScoringTypeId)		REFERENCES ScoringType(ScoringtypeId)
)