// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using KTC_Scraper.Models;
using Microsoft.EntityFrameworkCore;
using System;

namespace KTC_Scraper.Interfaces
{
    public interface IKtcContextContext : IDisposable 
    {
        DbSet<NflSchedule> NflSchedules { get; set; }
        DbSet<OneQbValue> OneQbValues { get; set; }
        DbSet<Player> Players { get; set; }
        DbSet<SuperflexValue> SuperflexValues { get; set; }
        DbSet<Team> Teams { get; set; }
        int SaveChanges();
    }
}