// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace KTC_Scraper.Models
{
    [Table("NflSchedule")]
    public partial class NflSchedule
    {
        public NflSchedule()
        {
            Players = new HashSet<Player>();
            Teams = new HashSet<Team>();
        }

        [Key]
        public int NflscheduleId { get; set; }
        public string kickoff { get; set; }
        public string gameSecondsRemaining { get; set; }

        [InverseProperty("Nflschedule")]
        public virtual ICollection<Player> Players { get; set; }
        [InverseProperty("Nflschedule")]
        public virtual ICollection<Team> Teams { get; set; }
    }
}