// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace KTC_Scraper.Models
{
    public partial class OneQbValue
    {
        public OneQbValue()
        {
            Players = new HashSet<Player>();
        }

        [Key]
        public int OneQbValuesId { get; set; }
        public int value { get; set; }
        public int startSitValue { get; set; }
        public int rank { get; set; }
        public int? overallTrend { get; set; }
        public int? positionalTrend { get; set; }
        public int? rookieTrend { get; set; }
        public int? rookiePositionalTrend { get; set; }
        public int? positionalRank { get; set; }
        public int? rookieRank { get; set; }
        public int? rookiePositionalRank { get; set; }
        public int kept { get; set; }
        public int traded { get; set; }
        public int cut { get; set; }
        public int diff { get; set; }
        public int? overallTier { get; set; }
        public int? positionalTier { get; set; }
        public int? rookieTier { get; set; }
        public int? rookiePositionalTier { get; set; }
        public int? overall7DayTrend { get; set; }
        public int? positional7DayTrend { get; set; }
        public int? startSitOverallRank { get; set; }
        public int? startSitPositionalRank { get; set; }
        public int? startSitOverallTier { get; set; }
        public int? startSitPositionalTier { get; set; }
        public int? startSitOneQBFlexTier { get; set; }
        public int? startSitSuperflexFlexTier { get; set; }
        public bool? isOutThisWeek { get; set; }

        [InverseProperty("OneQbValues")]
        public virtual ICollection<Player> Players { get; set; }
    }
}