// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using IndexAttribute = Microsoft.EntityFrameworkCore.IndexAttribute;

namespace KTC_Scraper.Models
{
    [Table("Team")]
    [Index("NflscheduleId", Name = "IX_Team_NflscheduleId")]
    public partial class Team
    {
        [Key]
        public int TeamId { get; set; }
        public string inRedZone { get; set; }
        public string score { get; set; }
        public string hasPossession { get; set; }
        public string passOffenseRank { get; set; }
        public string rushOffenseRank { get; set; }
        public string passDefenseRank { get; set; }
        public string spread { get; set; }
        public string isHome { get; set; }
        public string id { get; set; }
        public string rushDefenseRank { get; set; }
        public int? NflscheduleId { get; set; }

        [ForeignKey("NflscheduleId")]
        [InverseProperty("Teams")]
        public virtual NflSchedule Nflschedule { get; set; }
    }
}